version: '3.8'

services:
    php-cli:
        build:
            context: ./docker/php-cli
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ./:/app

    php-fpm:
        build:
            context: ./docker/php-fpm
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ./:/app
        extra_hosts:
            - "host.docker.internal:host-gateway" #Нужно для xdebug'a

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./logs/nginx/error.log:/var/log/nginx/error.log
        depends_on:
            - php-fpm
            - database
        ports:
            - "88:80"

    database:
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        ports:
            - "${POSTGRES_PORT}:5432"

volumes:
    pgdata: